#!/bin/sh
#
# Author: Kari Seppänen (c) 1996 (Kari.Seppanen@hut.fi)
#
# Tools for GB
#
# $Header: /localdisk2/users/kse/bin/RCS/atmos,v 1.2 1996/07/30 10:53:29 kse Exp kse $
#
# atmos - reads 'repo a' output and prints out commands to load fuel
#
# Usage (in gbII - client):
#				cd /
#				repo W | atmos > as
#				source as
#

sed 's/ [ ]*/ /g' | cut -d ' ' -f 9 | uniq | grep "^/" | awk 'NF > 0 {printf("cd %s\nload a f 3\n", $0)}'
